### ISSUE TITLE
Commit time shows year = 1970

### ISSUE THREAD

**Issue by jleni** [ZondaX/ledger-matrix#1]
In some case, commit time shows date with year equal to 1970

**Comment by jleni** [comment]
@yharvey 
Do you have by change the timestamp that you were using?

**Comment by yharvey** [comment]
Timestamp is in second. If  i use milliseconds is ok

**Comment by jleni** [comment]
The code is for seconds..
https://github.com/ZondaX/ledger-matrix/blob/9dab6e604eee426576b6e82c7da26662e5e47f45/tests/utils.cpp#L85

and the tests are also that way..

**Comment by jleni** [comment]
Ok, I could reproduce. Looking at it now

**Comment by yharvey** [comment]
ok
