### ISSUE TITLE
MANTX_ERROR_INVALID_TXTYPE (Error -7)

### ISSUE THREAD

**Issue by jleni** [ZondaX/ledger-matrix#2]
It seems this happens when extra_to is 9

**Comment by yharvey** [comment]
@jleni ，i tested other values，and 2 ，6，and 7 also show errors of -7.

**Comment by jleni** [comment]
@yharvey 

Transactions are being classified as:
- No Data Field
- JSON Data Field
- Hex Data Field

There are some types that are still unclear
To which group do the following types belong to?

#define MANTX_TXTYPE_MINER_REWARD       2
#define MANTX_TXTYPE_CANCEL_AUTH        6
#define MANTX_TXTYPE_CREATE_CURR        9
#define MANTX_TXTYPE_VERIF_REWARD       10
#define MANTX_TXTYPE_INTEREST_REWARD    11
#define MANTX_TXTYPE_TXFEE_REWARD       12
#define MANTX_TXTYPE_LOTTERY_REWARD     13
#define MANTX_TXTYPE_SET_BLACKLIST      14
#define MANTX_TXTYPE_SUPERBLOCK         122

**Comment by yharvey** [comment]
that depends on the extra_to's first field.
