### ISSUE TITLE
Missing docs (MD) from links in readme.md

### ISSUE THREAD

**Issue by JoeyDieleman78** [Zondax/ledger-matrix#4]
Hi, 

If browse the readme the following links are faulty:

### Matrix App

- [APDU Protocol](https://github.com/zondax/ledger-matrix/tree/master/docs/APDUSPEC.md)
- [Transaction format](https://github.com/zondax/ledger-matrix/tree/master/docs/TXSPEC.md)
- [User interface](https://github.com/zondax/ledger-matrix/tree/master/docs/UISPEC.md)

**Comment by jleni** [comment]
This issue seems stale. Closing now
