### ISSUE TITLE
Cannot open app in the 1.6.0 firmware

### ISSUE THREAD

**Issue by yharvey** [Zondax/ledger-matrix#5]
Cannot open app in the 1.6.0 firmware

**Comment by jleni** [comment]
Ledger firmware 1.6 is not backwards compatible. In order to support firmware 1.6, the app needs to be upgraded to SDK 1.6 and some changes are required.

**Comment by jleni** [comment]
could you start testing latest? It has been upgraded to 1.6 firmware.
